<?php
    require dirname(__DIR__).'/app/Core/helpers.php';
    spl_autoload_register(function($class){
        $prefix='Blue\\';
        if(str_starts_with($class,$prefix)){
            $path=dirname(__DIR__).'/app/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';
            if(is_file($path)) require $path;
        }
    });
    if(!is_file(dirname(__DIR__).'/.env') && basename($_SERVER['SCRIPT_NAME'])!=='install.php'){ header('Location: ../install.php'); exit; }
    session_name(config('app.session_name')); session_start();
    $path='/'.trim(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH),'/');
    $base=trim(parse_url(config('app.url'),PHP_URL_PATH)??'','/');
    if($base && str_starts_with(trim($path,'/'),$base)) $path='/'.trim(substr(trim($path,'/'),strlen($base)),'/');
    if($path==='/') $path='/dashboard';
    $public=['/login','/authenticate','/api/webhook'];
    if(!in_array($path,$public,true) && empty($_SESSION['user'])) redirect('/login');
    $r=new \Blue\Core\Router();
    $r->get('/login',[\Blue\Controllers\AuthController::class,'login']); $r->post('/authenticate',[\Blue\Controllers\AuthController::class,'authenticate']); $r->get('/logout',[\Blue\Controllers\AuthController::class,'logout']);
    $r->get('/dashboard',[\Blue\Controllers\DashboardController::class,'index']);
    $r->post('/api/webhook',[\Blue\Controllers\ApiController::class,'webhook']);
    $mc=new \Blue\Controllers\ModuleController();
    $r->get('/user-management', function() use ($mc){ $mc->index('user-management'); });
$r->post('/user-management/store', function() use ($mc){ $mc->store('user-management'); });
$r->get('/user-management/settings', function() use ($mc){ $mc->settings('user-management'); });
$r->post('/user-management/settings/save', function() use ($mc){ $mc->saveSetting('user-management'); });
$r->get('/user-management/report', function() use ($mc){ $mc->report('user-management'); });
$r->get('/organization', function() use ($mc){ $mc->index('organization'); });
$r->post('/organization/store', function() use ($mc){ $mc->store('organization'); });
$r->get('/organization/settings', function() use ($mc){ $mc->settings('organization'); });
$r->post('/organization/settings/save', function() use ($mc){ $mc->saveSetting('organization'); });
$r->get('/organization/report', function() use ($mc){ $mc->report('organization'); });
$r->get('/employee', function() use ($mc){ $mc->index('employee'); });
$r->post('/employee/store', function() use ($mc){ $mc->store('employee'); });
$r->get('/employee/settings', function() use ($mc){ $mc->settings('employee'); });
$r->post('/employee/settings/save', function() use ($mc){ $mc->saveSetting('employee'); });
$r->get('/employee/report', function() use ($mc){ $mc->report('employee'); });
$r->get('/recruitment', function() use ($mc){ $mc->index('recruitment'); });
$r->post('/recruitment/store', function() use ($mc){ $mc->store('recruitment'); });
$r->get('/recruitment/settings', function() use ($mc){ $mc->settings('recruitment'); });
$r->post('/recruitment/settings/save', function() use ($mc){ $mc->saveSetting('recruitment'); });
$r->get('/recruitment/report', function() use ($mc){ $mc->report('recruitment'); });
$r->get('/onboarding', function() use ($mc){ $mc->index('onboarding'); });
$r->post('/onboarding/store', function() use ($mc){ $mc->store('onboarding'); });
$r->get('/onboarding/settings', function() use ($mc){ $mc->settings('onboarding'); });
$r->post('/onboarding/settings/save', function() use ($mc){ $mc->saveSetting('onboarding'); });
$r->get('/onboarding/report', function() use ($mc){ $mc->report('onboarding'); });
$r->get('/attendance', function() use ($mc){ $mc->index('attendance'); });
$r->post('/attendance/store', function() use ($mc){ $mc->store('attendance'); });
$r->get('/attendance/settings', function() use ($mc){ $mc->settings('attendance'); });
$r->post('/attendance/settings/save', function() use ($mc){ $mc->saveSetting('attendance'); });
$r->get('/attendance/report', function() use ($mc){ $mc->report('attendance'); });
$r->get('/leave', function() use ($mc){ $mc->index('leave'); });
$r->post('/leave/store', function() use ($mc){ $mc->store('leave'); });
$r->get('/leave/settings', function() use ($mc){ $mc->settings('leave'); });
$r->post('/leave/settings/save', function() use ($mc){ $mc->saveSetting('leave'); });
$r->get('/leave/report', function() use ($mc){ $mc->report('leave'); });
$r->get('/overtime', function() use ($mc){ $mc->index('overtime'); });
$r->post('/overtime/store', function() use ($mc){ $mc->store('overtime'); });
$r->get('/overtime/settings', function() use ($mc){ $mc->settings('overtime'); });
$r->post('/overtime/settings/save', function() use ($mc){ $mc->saveSetting('overtime'); });
$r->get('/overtime/report', function() use ($mc){ $mc->report('overtime'); });
$r->get('/timesheet', function() use ($mc){ $mc->index('timesheet'); });
$r->post('/timesheet/store', function() use ($mc){ $mc->store('timesheet'); });
$r->get('/timesheet/settings', function() use ($mc){ $mc->settings('timesheet'); });
$r->post('/timesheet/settings/save', function() use ($mc){ $mc->saveSetting('timesheet'); });
$r->get('/timesheet/report', function() use ($mc){ $mc->report('timesheet'); });
$r->get('/payroll', function() use ($mc){ $mc->index('payroll'); });
$r->post('/payroll/store', function() use ($mc){ $mc->store('payroll'); });
$r->get('/payroll/settings', function() use ($mc){ $mc->settings('payroll'); });
$r->post('/payroll/settings/save', function() use ($mc){ $mc->saveSetting('payroll'); });
$r->get('/payroll/report', function() use ($mc){ $mc->report('payroll'); });
$r->get('/approval', function() use ($mc){ $mc->index('approval'); });
$r->post('/approval/store', function() use ($mc){ $mc->store('approval'); });
$r->get('/approval/settings', function() use ($mc){ $mc->settings('approval'); });
$r->post('/approval/settings/save', function() use ($mc){ $mc->saveSetting('approval'); });
$r->get('/approval/report', function() use ($mc){ $mc->report('approval'); });
$r->get('/documents', function() use ($mc){ $mc->index('documents'); });
$r->post('/documents/store', function() use ($mc){ $mc->store('documents'); });
$r->get('/documents/settings', function() use ($mc){ $mc->settings('documents'); });
$r->post('/documents/settings/save', function() use ($mc){ $mc->saveSetting('documents'); });
$r->get('/documents/report', function() use ($mc){ $mc->report('documents'); });
$r->get('/facility-benefit', function() use ($mc){ $mc->index('facility-benefit'); });
$r->post('/facility-benefit/store', function() use ($mc){ $mc->store('facility-benefit'); });
$r->get('/facility-benefit/settings', function() use ($mc){ $mc->settings('facility-benefit'); });
$r->post('/facility-benefit/settings/save', function() use ($mc){ $mc->saveSetting('facility-benefit'); });
$r->get('/facility-benefit/report', function() use ($mc){ $mc->report('facility-benefit'); });
$r->get('/performance', function() use ($mc){ $mc->index('performance'); });
$r->post('/performance/store', function() use ($mc){ $mc->store('performance'); });
$r->get('/performance/settings', function() use ($mc){ $mc->settings('performance'); });
$r->post('/performance/settings/save', function() use ($mc){ $mc->saveSetting('performance'); });
$r->get('/performance/report', function() use ($mc){ $mc->report('performance'); });
$r->get('/training', function() use ($mc){ $mc->index('training'); });
$r->post('/training/store', function() use ($mc){ $mc->store('training'); });
$r->get('/training/settings', function() use ($mc){ $mc->settings('training'); });
$r->post('/training/settings/save', function() use ($mc){ $mc->saveSetting('training'); });
$r->get('/training/report', function() use ($mc){ $mc->report('training'); });
$r->get('/google-drive', function() use ($mc){ $mc->index('google-drive'); });
$r->post('/google-drive/store', function() use ($mc){ $mc->store('google-drive'); });
$r->get('/google-drive/settings', function() use ($mc){ $mc->settings('google-drive'); });
$r->post('/google-drive/settings/save', function() use ($mc){ $mc->saveSetting('google-drive'); });
$r->get('/google-drive/report', function() use ($mc){ $mc->report('google-drive'); });
$r->get('/whats-app', function() use ($mc){ $mc->index('whats-app'); });
$r->post('/whats-app/store', function() use ($mc){ $mc->store('whats-app'); });
$r->get('/whats-app/settings', function() use ($mc){ $mc->settings('whats-app'); });
$r->post('/whats-app/settings/save', function() use ($mc){ $mc->saveSetting('whats-app'); });
$r->get('/whats-app/report', function() use ($mc){ $mc->report('whats-app'); });
$r->get('/a-i-analytics', function() use ($mc){ $mc->index('a-i-analytics'); });
$r->post('/a-i-analytics/store', function() use ($mc){ $mc->store('a-i-analytics'); });
$r->get('/a-i-analytics/settings', function() use ($mc){ $mc->settings('a-i-analytics'); });
$r->post('/a-i-analytics/settings/save', function() use ($mc){ $mc->saveSetting('a-i-analytics'); });
$r->get('/a-i-analytics/report', function() use ($mc){ $mc->report('a-i-analytics'); });
$r->get('/blue-hub-integration', function() use ($mc){ $mc->index('blue-hub-integration'); });
$r->post('/blue-hub-integration/store', function() use ($mc){ $mc->store('blue-hub-integration'); });
$r->get('/blue-hub-integration/settings', function() use ($mc){ $mc->settings('blue-hub-integration'); });
$r->post('/blue-hub-integration/settings/save', function() use ($mc){ $mc->saveSetting('blue-hub-integration'); });
$r->get('/blue-hub-integration/report', function() use ($mc){ $mc->report('blue-hub-integration'); });
$r->get('/reports', function() use ($mc){ $mc->index('reports'); });
$r->post('/reports/store', function() use ($mc){ $mc->store('reports'); });
$r->get('/reports/settings', function() use ($mc){ $mc->settings('reports'); });
$r->post('/reports/settings/save', function() use ($mc){ $mc->saveSetting('reports'); });
$r->get('/reports/report', function() use ($mc){ $mc->report('reports'); });
$r->get('/settings', function() use ($mc){ $mc->index('settings'); });
$r->post('/settings/store', function() use ($mc){ $mc->store('settings'); });
$r->get('/settings/settings', function() use ($mc){ $mc->settings('settings'); });
$r->post('/settings/settings/save', function() use ($mc){ $mc->saveSetting('settings'); });
$r->get('/settings/report', function() use ($mc){ $mc->report('settings'); });

// Specific operational User Management routes override the generic module routes.
$r->get('/user-management',[\Blue\Controllers\UserManagementController::class,'index']);
$r->get('/user-management/create',[\Blue\Controllers\UserManagementController::class,'create']);
$r->post('/user-management/store',[\Blue\Controllers\UserManagementController::class,'store']);
$r->get('/user-management/edit',[\Blue\Controllers\UserManagementController::class,'edit']);
$r->post('/user-management/update',[\Blue\Controllers\UserManagementController::class,'update']);
$r->post('/user-management/deactivate',[\Blue\Controllers\UserManagementController::class,'deactivate']);
$r->post('/user-management/delete',[\Blue\Controllers\UserManagementController::class,'delete']);
$r->dispatch($path);
