<?php
require dirname(__DIR__) . '/app/Core/helpers.php';
spl_autoload_register(function($class){
    $prefix='BlueHR\\';
    if (str_starts_with($class,$prefix)) {
        $path=dirname(__DIR__) . '/app/' . str_replace('\\','/',substr($class,strlen($prefix))) . '.php';
        if (is_file($path)) require $path;
    }
});
use BlueHR\Core\Database;
$today = date('Y-m-d');
if (Database::first('SELECT id FROM public_holidays WHERE holiday_date=? LIMIT 1', [$today])) { echo "Holiday, skipped.\n"; exit; }
$employees = Database::query('SELECT id FROM employees WHERE status="active"');
foreach ($employees as $employee) {
    $id = $employee['id'];
    $leave = Database::first('SELECT id FROM leave_requests WHERE employee_id=? AND status="approved" AND ? BETWEEN start_date AND end_date LIMIT 1', [$id, $today]);
    if ($leave) continue;
    $exists = Database::first('SELECT id FROM attendance_logs WHERE employee_id=? AND attendance_date=? LIMIT 1', [$id, $today]);
    if ($exists) continue;
    Database::execute('INSERT INTO attendance_logs(employee_id,attendance_date,status,source,auto_generated,notes,created_at) VALUES(?,?,?,?,?,?,NOW())', [$id,$today,'auto_present','auto',1,'Generated by auto attendance cron']);
}
echo "Auto attendance completed.\n";
