SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS companies (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,legal_name VARCHAR(200),tax_number VARCHAR(50),address TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS users (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,email VARCHAR(150) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,employee_id BIGINT NULL,status ENUM('active','inactive','locked') DEFAULT 'active',last_login_at DATETIME NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS roles (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL UNIQUE,description TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS permissions (id BIGINT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(120) NOT NULL UNIQUE,name VARCHAR(150) NOT NULL,module VARCHAR(100) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS user_roles (user_id BIGINT NOT NULL,role_id BIGINT NOT NULL,PRIMARY KEY(user_id,role_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS role_permissions (role_id BIGINT NOT NULL,permission_id BIGINT NOT NULL,PRIMARY KEY(role_id,permission_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS app_settings (id BIGINT AUTO_INCREMENT PRIMARY KEY,setting_key VARCHAR(120) NOT NULL UNIQUE,setting_value TEXT NULL,setting_group VARCHAR(80) DEFAULT 'general',updated_at DATETIME NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS audit_logs (id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NULL,action VARCHAR(150),entity_type VARCHAR(100),entity_id BIGINT NULL,context_json JSON NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS branches (id BIGINT AUTO_INCREMENT PRIMARY KEY,company_id BIGINT NOT NULL DEFAULT 1,code VARCHAR(50) NOT NULL,name VARCHAR(150) NOT NULL,manager_employee_id BIGINT NULL,cost_center VARCHAR(100) NULL,accurate_branch_id VARCHAR(100),status VARCHAR(50) DEFAULT 'active',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS departments (id BIGINT AUTO_INCREMENT PRIMARY KEY,company_id BIGINT NOT NULL DEFAULT 1,code VARCHAR(50) NOT NULL,name VARCHAR(150) NOT NULL,parent_id BIGINT NULL,manager_employee_id BIGINT NULL,cost_center VARCHAR(100) NULL,accurate_department_id VARCHAR(100),salary_expense_account_id BIGINT NULL,status VARCHAR(50) DEFAULT 'active',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS job_levels (id BIGINT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(50),name VARCHAR(100),rank_no INT DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS employment_types (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),is_permanent TINYINT DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS positions (id BIGINT AUTO_INCREMENT PRIMARY KEY,department_id BIGINT NULL,name VARCHAR(150) NOT NULL,grade VARCHAR(50),job_level_id BIGINT NULL,employment_type_id BIGINT NULL,status VARCHAR(50) DEFAULT 'active',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS work_locations (id BIGINT AUTO_INCREMENT PRIMARY KEY,company_id BIGINT NOT NULL DEFAULT 1,name VARCHAR(150),address TEXT,type VARCHAR(50) DEFAULT 'office',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS working_schedules (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120),flexible_enabled TINYINT DEFAULT 0,auto_attendance_enabled TINYINT DEFAULT 0,min_hours DECIMAL(5,2) DEFAULT 8,core_start TIME NULL,core_end TIME NULL,timezone VARCHAR(80) DEFAULT 'Asia/Jakarta',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS departure_reasons (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),description TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS employees (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_no VARCHAR(50) NOT NULL UNIQUE,full_name VARCHAR(150) NOT NULL,photo_path VARCHAR(255) NULL,email VARCHAR(150),phone VARCHAR(50),whatsapp VARCHAR(50),gender ENUM('male','female') NULL,birth_place VARCHAR(100),birth_date DATE,address TEXT,nik VARCHAR(50),npwp VARCHAR(50),marital_status VARCHAR(50),bank_name VARCHAR(100),bank_account_no VARCHAR(100),bank_account_name VARCHAR(150),company_id BIGINT NOT NULL DEFAULT 1,branch_id BIGINT NULL,department_id BIGINT NULL,position_id BIGINT NULL,job_level_id BIGINT NULL,employment_type_id BIGINT NULL,work_location_id BIGINT NULL,working_schedule_id BIGINT NULL,supervisor_id BIGINT NULL,departure_reason_id BIGINT NULL,employment_status ENUM('permanent','contract','probation','intern','freelance') DEFAULT 'permanent',join_date DATE NOT NULL,resign_date DATE NULL,status ENUM('active','inactive','resigned') DEFAULT 'active',accurate_employee_id VARCHAR(100),created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS employee_job_movements (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT NOT NULL,effective_date DATE NOT NULL,old_branch_id BIGINT NULL,new_branch_id BIGINT NULL,old_department_id BIGINT NULL,new_department_id BIGINT NULL,old_position_id BIGINT NULL,new_position_id BIGINT NULL,old_job_level_id BIGINT NULL,new_job_level_id BIGINT NULL,reason TEXT,approved_by BIGINT NULL,attachment_path VARCHAR(255) NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS employee_working_info (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT NOT NULL,location VARCHAR(150),work_address TEXT,timeoff_approver_id BIGINT NULL,timesheet_approver_id BIGINT NULL,attendance_approver_id BIGINT NULL,monday_location VARCHAR(100),tuesday_location VARCHAR(100),wednesday_location VARCHAR(100),thursday_location VARCHAR(100),friday_location VARCHAR(100),saturday_location VARCHAR(100),sunday_location VARCHAR(100),working_hours VARCHAR(100),timezone VARCHAR(80),planning_roles TEXT,default_role VARCHAR(100)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS employee_private_contacts (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT NOT NULL,private_address TEXT,private_email VARCHAR(150),private_phone VARCHAR(50),bank_account VARCHAR(150),home_work_distance DECIMAL(10,2),private_car_plate VARCHAR(50),nationality_country VARCHAR(100),identification_no VARCHAR(100),ssn_no VARCHAR(100),passport_no VARCHAR(100),gender VARCHAR(20),date_of_birth DATE,place_of_birth VARCHAR(100),country_of_birth VARCHAR(100),emergency_contact_name VARCHAR(150),emergency_contact_phone VARCHAR(50),marital_status VARCHAR(50),spouse_name VARCHAR(150),spouse_birthdate DATE,dependent_children INT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS employee_education (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT,certificate_level VARCHAR(100),field_of_study VARCHAR(150),school VARCHAR(150),start_year INT,end_year INT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS employee_work_permits (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT,visa_no VARCHAR(100),work_permit_no VARCHAR(100),visa_expiration_date DATE,work_permit_expiration_date DATE,permit_file_path VARCHAR(255)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS employee_contracts (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT NOT NULL,contract_no VARCHAR(100) NOT NULL,contract_type VARCHAR(100) NOT NULL,start_date DATE NOT NULL,end_date DATE,file_path VARCHAR(255),status ENUM('active','expired','terminated') DEFAULT 'active',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS skill_types (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS employee_skills (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT,skill_type_id BIGINT,skill_name VARCHAR(150),level_name VARCHAR(50)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS tags (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(80),color VARCHAR(20)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS employee_tags (employee_id BIGINT,tag_id BIGINT,PRIMARY KEY(employee_id,tag_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS activity_plans (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT,title VARCHAR(150),description TEXT,due_date DATE,status VARCHAR(50) DEFAULT 'open') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS line_types (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),description TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS shift_templates (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,start_time TIME,end_time TIME,break_minutes INT DEFAULT 60,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS attendance_logs (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT NOT NULL,attendance_date DATE NOT NULL,check_in DATETIME NULL,check_out DATETIME NULL,status ENUM('present','absent','late','leave','holiday','sick','auto_present') DEFAULT 'present',source ENUM('manual','import','device','mobile','auto') DEFAULT 'manual',auto_generated TINYINT DEFAULT 0,notes TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,INDEX(employee_id,attendance_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS public_holidays (id BIGINT AUTO_INCREMENT PRIMARY KEY,holiday_date DATE NOT NULL,name VARCHAR(150),type ENUM('national','collective','company') DEFAULT 'national') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS leave_types (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,annual_quota DECIMAL(6,2) DEFAULT 0,is_paid BOOLEAN DEFAULT TRUE,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS leave_reasons (id BIGINT AUTO_INCREMENT PRIMARY KEY,leave_type_id BIGINT,name VARCHAR(150),is_active TINYINT DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS leave_allocations (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT,leave_type_id BIGINT,period_year INT,allocated DECIMAL(6,2),used DECIMAL(6,2) DEFAULT 0,pending DECIMAL(6,2) DEFAULT 0,expired_at DATE NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS leave_requests (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT NOT NULL,leave_type_id BIGINT NOT NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,total_days DECIMAL(6,2) NOT NULL,reason TEXT,status ENUM('draft','pending','approved','rejected','cancelled') DEFAULT 'pending',approved_by BIGINT NULL,approved_at DATETIME NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS overtime_requests (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT NOT NULL,overtime_date DATE NOT NULL,start_time TIME NOT NULL,end_time TIME NOT NULL,total_hours DECIMAL(6,2) NOT NULL,reason TEXT,status ENUM('pending','approved','rejected') DEFAULT 'pending',approved_by BIGINT NULL,approved_at DATETIME NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS candidates (id BIGINT AUTO_INCREMENT PRIMARY KEY,full_name VARCHAR(150),email VARCHAR(150),phone VARCHAR(50),position_applied VARCHAR(150),stage VARCHAR(50) DEFAULT 'screening',status VARCHAR(50) DEFAULT 'active',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS onboarding_tasks (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT,task_name VARCHAR(150),due_date DATE,status VARCHAR(50) DEFAULT 'open',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS training_programs (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150),start_date DATE,end_date DATE,budget DECIMAL(18,2) DEFAULT 0,status VARCHAR(50) DEFAULT 'planned',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS salary_components (id BIGINT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(50) NOT NULL UNIQUE,name VARCHAR(150) NOT NULL,type ENUM('earning','deduction','company_contribution') NOT NULL,calculation_type ENUM('fixed','formula','manual') DEFAULT 'fixed',default_amount DECIMAL(18,2) DEFAULT 0,taxable BOOLEAN DEFAULT TRUE,accurate_account_id BIGINT NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS employee_salary_components (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT NOT NULL,component_id BIGINT NOT NULL,amount DECIMAL(18,2) NOT NULL DEFAULT 0,effective_date DATE NOT NULL,end_date DATE NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS payroll_periods (id BIGINT AUTO_INCREMENT PRIMARY KEY,company_id BIGINT NOT NULL,period_month TINYINT NOT NULL,period_year SMALLINT NOT NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,status ENUM('draft','processing','calculated','approved','posted','closed') DEFAULT 'draft',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS payroll_runs (id BIGINT AUTO_INCREMENT PRIMARY KEY,payroll_period_id BIGINT NOT NULL,run_no VARCHAR(100) NOT NULL,status ENUM('draft','calculated','approved','posted_to_accurate','failed') DEFAULT 'draft',total_gross DECIMAL(18,2) DEFAULT 0,total_deduction DECIMAL(18,2) DEFAULT 0,total_tax DECIMAL(18,2) DEFAULT 0,total_net DECIMAL(18,2) DEFAULT 0,approved_by BIGINT NULL,approved_at DATETIME NULL,posted_to_accurate_at DATETIME NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS payroll_lines (id BIGINT AUTO_INCREMENT PRIMARY KEY,payroll_run_id BIGINT NOT NULL,employee_id BIGINT NOT NULL,basic_salary DECIMAL(18,2) DEFAULT 0,total_allowance DECIMAL(18,2) DEFAULT 0,total_overtime DECIMAL(18,2) DEFAULT 0,total_deduction DECIMAL(18,2) DEFAULT 0,bpjs_employee DECIMAL(18,2) DEFAULT 0,bpjs_company DECIMAL(18,2) DEFAULT 0,pph21 DECIMAL(18,2) DEFAULT 0,take_home_pay DECIMAL(18,2) DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS payroll_line_components (id BIGINT AUTO_INCREMENT PRIMARY KEY,payroll_line_id BIGINT NOT NULL,component_id BIGINT NOT NULL,component_name VARCHAR(150) NOT NULL,type ENUM('earning','deduction','company_contribution') NOT NULL,amount DECIMAL(18,2) NOT NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS payroll_journals (id BIGINT AUTO_INCREMENT PRIMARY KEY,payroll_run_id BIGINT NOT NULL,journal_no VARCHAR(100) NOT NULL,journal_date DATE NOT NULL,description TEXT,status ENUM('draft','validated','posted_to_accurate','failed') DEFAULT 'draft',accurate_journal_id VARCHAR(100),accurate_journal_number VARCHAR(100),error_message TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS payroll_journal_lines (id BIGINT AUTO_INCREMENT PRIMARY KEY,payroll_journal_id BIGINT NOT NULL,account_mapping_id BIGINT NOT NULL,description VARCHAR(255),debit DECIMAL(18,2) DEFAULT 0,credit DECIMAL(18,2) DEFAULT 0,department_id BIGINT NULL,branch_id BIGINT NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reimbursements (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT,claim_type VARCHAR(100),amount DECIMAL(18,2),description TEXT,status VARCHAR(50) DEFAULT 'pending',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS employee_loans (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT,loan_no VARCHAR(100),principal DECIMAL(18,2),outstanding DECIMAL(18,2),installment DECIMAL(18,2),status VARCHAR(50) DEFAULT 'active',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS performance_periods (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150),start_date DATE,end_date DATE,review_start_date DATE,review_deadline DATE,status VARCHAR(50) DEFAULT 'draft',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS performance_templates (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150),applicable_department_id BIGINT NULL,applicable_job_level_id BIGINT NULL,description TEXT,is_active TINYINT DEFAULT 1,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS performance_kpi_library (id BIGINT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(50),name VARCHAR(150),description TEXT,measurement_unit VARCHAR(80),target_type VARCHAR(50),target_value VARCHAR(150),weight DECIMAL(6,2) DEFAULT 0,department_id BIGINT NULL,position_id BIGINT NULL,is_active TINYINT DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS performance_competency_library (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150),category VARCHAR(100),description TEXT,level_name VARCHAR(80),behavioral_indicator TEXT,weight DECIMAL(6,2) DEFAULT 0,is_active TINYINT DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS performance_goals (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT,objective VARCHAR(255),key_result VARCHAR(255),target VARCHAR(150),progress DECIMAL(6,2) DEFAULT 0,due_date DATE,status VARCHAR(50) DEFAULT 'not_started',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS performance_reviews (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT,period_id BIGINT NULL,review_type VARCHAR(50) DEFAULT 'manager',kpi_score DECIMAL(8,2) DEFAULT 0,competency_score DECIMAL(8,2) DEFAULT 0,goal_score DECIMAL(8,2) DEFAULT 0,attendance_score DECIMAL(8,2) DEFAULT 0,final_score DECIMAL(8,2) DEFAULT 0,rating VARCHAR(80),status VARCHAR(50) DEFAULT 'draft',manager_comment TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS performance_calibrations (id BIGINT AUTO_INCREMENT PRIMARY KEY,review_id BIGINT,calibrated_score DECIMAL(8,2),final_rating VARCHAR(80),notes TEXT,approved_by BIGINT NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS performance_improvement_plans (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT,issue_gap TEXT,expected_improvement TEXT,action_plan TEXT,start_date DATE,end_date DATE,mentor_user_id BIGINT NULL,status VARCHAR(50) DEFAULT 'open',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS performance_bonus_rules (id BIGINT AUTO_INCREMENT PRIMARY KEY,rating VARCHAR(80),min_score DECIMAL(8,2),max_score DECIMAL(8,2),multiplier DECIMAL(8,2),max_bonus DECIMAL(18,2),minimum_working_months INT DEFAULT 0,payroll_component_code VARCHAR(80),is_active TINYINT DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS performance_bonus_recommendations (id BIGINT AUTO_INCREMENT PRIMARY KEY,review_id BIGINT,employee_id BIGINT,amount DECIMAL(18,2),status VARCHAR(50) DEFAULT 'draft',created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS approval_types (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120),code VARCHAR(80) UNIQUE,description TEXT,requires_amount TINYINT DEFAULT 0,requires_attachment TINYINT DEFAULT 0,is_active TINYINT DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS approval_type_fields (id BIGINT AUTO_INCREMENT PRIMARY KEY,approval_type_id BIGINT,field_key VARCHAR(100),field_label VARCHAR(150),field_type VARCHAR(50),is_required TINYINT DEFAULT 0,options_json JSON NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS approval_steps (id BIGINT AUTO_INCREMENT PRIMARY KEY,approval_type_id BIGINT,step_order INT,approver_type ENUM('user','role','manager','department_manager') DEFAULT 'manager',approver_user_id BIGINT NULL,approver_role_id BIGINT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS approval_requests (id BIGINT AUTO_INCREMENT PRIMARY KEY,request_type_id BIGINT,requester_employee_id BIGINT,title VARCHAR(180),description TEXT,amount DECIMAL(18,2) DEFAULT 0,status ENUM('draft','pending','need_revision','approved','rejected','cancelled','completed') DEFAULT 'pending',payload_json JSON NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS approval_actions (id BIGINT AUTO_INCREMENT PRIMARY KEY,request_id BIGINT,approver_user_id BIGINT,action VARCHAR(50),notes TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS email_notifications (id BIGINT AUTO_INCREMENT PRIMARY KEY,to_email VARCHAR(150),subject VARCHAR(255),body TEXT,status VARCHAR(50) DEFAULT 'pending',sent_at DATETIME NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS facilities (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150),category VARCHAR(100),description TEXT,is_asset TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS facility_eligibility_rules (id BIGINT AUTO_INCREMENT PRIMARY KEY,facility_id BIGINT,job_level_id BIGINT,employment_type_id BIGINT NULL,is_eligible TINYINT DEFAULT 1,effective_start DATE,effective_end DATE NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS employee_facilities (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT,facility_id BIGINT,start_date DATE,end_date DATE,status ENUM('active','returned','expired') DEFAULT 'active',notes TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS insurances (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150),provider VARCHAR(150),description TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS employee_insurances (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT,insurance_id BIGINT,start_date DATE,end_date DATE,policy_no VARCHAR(100),status VARCHAR(50)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS challenges (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150),description TEXT,start_date DATE,end_date DATE,status VARCHAR(50) DEFAULT 'active') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS badges (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),description TEXT,icon VARCHAR(255)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS employee_badges (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT,badge_id BIGINT,awarded_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS goals_history (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT,goal_title VARCHAR(180),goal_period VARCHAR(100),progress DECIMAL(5,2),status VARCHAR(50),created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS uploaded_files (id BIGINT AUTO_INCREMENT PRIMARY KEY,employee_id BIGINT NULL,candidate_id BIGINT NULL,category VARCHAR(80),original_filename VARCHAR(255),storage_provider VARCHAR(50) DEFAULT 'local',local_path VARCHAR(255) NULL,gdrive_file_id VARCHAR(150) NULL,gdrive_view_link VARCHAR(255) NULL,uploaded_by BIGINT NULL,notes TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS whatsapp_templates (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),message TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ai_analysis_logs (id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NULL,employee_id BIGINT NULL,scope VARCHAR(80),prompt TEXT,response_summary TEXT,risk_level VARCHAR(40),created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS accurate_connections (id BIGINT AUTO_INCREMENT PRIMARY KEY,company_id BIGINT NOT NULL DEFAULT 1,client_id VARCHAR(255),client_secret_encrypted TEXT,redirect_uri VARCHAR(255),scope TEXT,status ENUM('draft','connected','expired','revoked','error') DEFAULT 'draft',accurate_user_email VARCHAR(150),connected_at DATETIME NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS accurate_tokens (id BIGINT AUTO_INCREMENT PRIMARY KEY,connection_id BIGINT NOT NULL,access_token_encrypted TEXT,refresh_token_encrypted TEXT,token_type VARCHAR(50) DEFAULT 'bearer',expires_at DATETIME NULL,last_refreshed_at DATETIME NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS accurate_databases (id BIGINT AUTO_INCREMENT PRIMARY KEY,connection_id BIGINT NOT NULL,accurate_database_id VARCHAR(100) NOT NULL,database_name VARCHAR(150) NOT NULL,host VARCHAR(255),session_id VARCHAR(255),is_active BOOLEAN DEFAULT FALSE,last_opened_at DATETIME NULL,last_redirect_at DATETIME NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS accurate_account_mappings (id BIGINT AUTO_INCREMENT PRIMARY KEY,company_id BIGINT NOT NULL DEFAULT 1,mapping_key VARCHAR(100) NOT NULL,local_name VARCHAR(150) NOT NULL,accurate_account_id VARCHAR(100) NOT NULL,accurate_account_no VARCHAR(100),accurate_account_name VARCHAR(150) NOT NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS accurate_sync_logs (id BIGINT AUTO_INCREMENT PRIMARY KEY,company_id BIGINT NOT NULL DEFAULT 1,entity_type VARCHAR(100) NOT NULL,entity_id BIGINT NOT NULL,action VARCHAR(100) NOT NULL,status ENUM('pending','success','failed','retrying') DEFAULT 'pending',request_payload JSON NULL,response_payload JSON NULL,error_message TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO companies(id,name,legal_name) VALUES (1,'Default Organization','Default Organization');
INSERT IGNORE INTO roles(id,name,description) VALUES (1,'Super Admin','Full access'),(2,'HR Manager','HR management'),(3,'HR Staff','HR operations'),(4,'Finance Manager','Finance approvals'),(5,'Payroll Officer','Payroll operations'),(6,'Department Manager','Team approvals'),(7,'Employee','Employee self-service'),(8,'Auditor','Read-only audit');
INSERT IGNORE INTO permissions(code,name,module) VALUES ('user.manage','Manage Users','System'),('employee.view','View Employees','Employee'),('employee.create','Create Employees','Employee'),('leave.request','Request Leave','Leave'),('leave.approve','Approve Leave','Leave'),('payroll.calculate','Calculate Payroll','Payroll'),('payroll.approve','Approve Payroll','Payroll'),('accurate.config','Configure Accurate','Accurate'),('ai.employee_analysis','AI Employee Analysis','AIAnalytics'),('performance.manage','Manage Performance','Performance');
INSERT IGNORE INTO job_levels(id,code,name,rank_no) VALUES (1,'STAFF','Staff',1),(2,'SPV','Supervisor',2),(3,'MGR','Manager',3),(4,'DIR','Director',4);
INSERT IGNORE INTO approval_types(id,name,code,description,requires_amount,requires_attachment) VALUES (1,'Leave','leave','Leave request approval',0,0),(2,'Overtime','overtime','Overtime approval',0,0),(3,'Procurement','procurement','Procurement request',1,1),(4,'Business Trip','business_trip','Duty trip request',1,1);
INSERT IGNORE INTO app_settings(setting_key,setting_value,setting_group) VALUES ('organization_name','BlueHR','company'),('organization_logo','','company'),('gdrive_enabled','0','google_drive'),('attendance_auto_generation','0','attendance'),('attendance_flexible_hours','0','attendance'),('ai_enabled','0','ai'),('performance_review_cycle','quarterly','performance'),('performance_scoring_method','percentage','performance');
