<?php namespace Blue\Controllers; use Blue\Core\Database; use Blue\Core\View; use Blue\Services\Audit;
class ModuleController {
  private function module($slug){ $m=Database::one('SELECT * FROM modules WHERE slug=?',[$slug]); if(!$m){ http_response_code(404); exit('Module not found'); } return $m; }
  public function index($slug){ $m=$this->module($slug); $schema=json_decode($m['fields_json'] ?: '[]',true); $records=Database::all('SELECT * FROM module_records WHERE module_slug=? ORDER BY id DESC LIMIT 200',[$slug]); View::render('module/index',['title'=>$m['name'],'module'=>$m,'schema'=>$schema,'records'=>$records]); }
  public function store($slug){ $m=$this->module($slug); $data=$_POST; unset($data['_csrf']); $summary=[]; foreach(json_decode($m['fields_json']?:'[]',true) as $f){ $summary[$f]=$data[$f]??''; } $id=Database::insert('INSERT INTO module_records(module_slug,title,data_json,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,NOW(),NOW())',[$slug,$summary[array_key_first($summary)]??$m['name'],json_encode($summary),$data['status']??'active',$_SESSION['user']['id']??null]); Audit::log('module_record.create',$slug,$id,$summary); flash('success','Data saved.'); redirect('/'.$slug); }
  public function settings($slug){ $m=$this->module($slug); $settings=Database::all('SELECT * FROM app_settings WHERE module_slug=? ORDER BY setting_key',[$slug]); View::render('module/settings',['title'=>$m['name'].' Settings','module'=>$m,'settings'=>$settings]); }
  public function saveSetting($slug){ $m=$this->module($slug); $key=trim($_POST['setting_key']??''); $val=$_POST['setting_value']??''; if(!$key){ flash('danger','Setting key is required.'); redirect('/'.$slug.'/settings'); } Database::exec('INSERT INTO app_settings(module_slug,setting_key,setting_value,setting_type,updated_at) VALUES(?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value), setting_type=VALUES(setting_type), updated_at=NOW()',[$slug,$key,$val,$_POST['setting_type']??'text']); Audit::log('setting.save',$slug,null,[$key=>$val]); flash('success','Setting saved.'); redirect('/'.$slug.'/settings'); }
  public function report($slug){ $m=$this->module($slug); $count=Database::one('SELECT COUNT(*) c FROM module_records WHERE module_slug=?',[$slug])['c']??0; View::render('module/report',['title'=>$m['name'].' Report','module'=>$m,'count'=>$count]); }
}
