<?php
namespace BlueHR\Controllers;
use BlueHR\Core\Controller;
use BlueHR\Core\Database;
use BlueHR\Services\Security\Audit;

class PerformanceController extends Controller
{
    private function all(string $sql,array $p=[]): array { try{return Database::all($sql,$p);}catch(\Throwable $e){return [];} }
    private function one(string $sql,array $p=[]): array { try{return Database::one($sql,$p)?:[];}catch(\Throwable $e){return [];} }
    private function employees(): array { return $this->all('SELECT id, employee_no, full_name FROM employees ORDER BY full_name LIMIT 500'); }
    public function dashboard(): void {
        $data=[
            'periods'=>$this->one('SELECT COUNT(*) c FROM performance_periods')['c']??0,
            'reviews'=>$this->one('SELECT COUNT(*) c FROM performance_reviews')['c']??0,
            'goals'=>$this->one('SELECT COUNT(*) c FROM performance_goals')['c']??0,
            'avg'=>$this->one('SELECT ROUND(AVG(final_score),2) c FROM performance_reviews')['c']??0,
            'reviews_list'=>$this->all('SELECT r.*, e.full_name employee_name FROM performance_reviews r LEFT JOIN employees e ON e.id=r.employee_id ORDER BY r.id DESC LIMIT 20')
        ];
        $this->view('performance/dashboard',['title'=>'Performance Management','data'=>$data]);
    }
    public function periods(): void { $this->view('performance/periods',['title'=>'Appraisal Periods','rows'=>$this->all('SELECT * FROM performance_periods ORDER BY id DESC')]); }
    public function storePeriod(): void { $id=Database::insert('INSERT INTO performance_periods(name,start_date,end_date,review_start_date,review_deadline,status,created_at) VALUES(?,?,?,?,?,?,NOW())',[trim($_POST['name']??''),$_POST['start_date']?:null,$_POST['end_date']?:null,$_POST['review_start_date']?:null,$_POST['review_deadline']?:null,$_POST['status']??'draft']); Audit::log('create_performance_period','performance_period',(int)$id,$_POST); flash('success','Appraisal period saved.'); redirect('/performance/periods'); }
    public function kpi(): void { $this->view('performance/kpi',['title'=>'KPI Library','rows'=>$this->all('SELECT * FROM performance_kpi_library ORDER BY id DESC')]); }
    public function storeKpi(): void { $id=Database::insert('INSERT INTO performance_kpi_library(code,name,description,measurement_unit,target_type,target_value,weight,department_id,position_id,is_active) VALUES(?,?,?,?,?,?,?,?,?,1)',[trim($_POST['code']??''),trim($_POST['name']??''),trim($_POST['description']??''),trim($_POST['measurement_unit']??''),trim($_POST['target_type']??'higher_is_better'),trim($_POST['target_value']??''),(float)($_POST['weight']??0),$_POST['department_id']?:null,$_POST['position_id']?:null]); Audit::log('create_kpi','performance_kpi',(int)$id,$_POST); flash('success','KPI saved.'); redirect('/performance/kpi'); }
    public function goals(): void { $this->view('performance/goals',['title'=>'Goals / OKR','rows'=>$this->all('SELECT g.*, e.full_name employee_name FROM performance_goals g LEFT JOIN employees e ON e.id=g.employee_id ORDER BY g.id DESC'),'employees'=>$this->employees()]); }
    public function storeGoal(): void { $id=Database::insert('INSERT INTO performance_goals(employee_id,objective,key_result,target,progress,due_date,status,created_at) VALUES(?,?,?,?,?,?,?,NOW())',[(int)($_POST['employee_id']??0),trim($_POST['objective']??''),trim($_POST['key_result']??''),trim($_POST['target']??''),(float)($_POST['progress']??0),$_POST['due_date']?:null,$_POST['status']??'not_started']); Audit::log('create_goal','performance_goal',(int)$id,$_POST); flash('success','Goal saved.'); redirect('/performance/goals'); }
    public function competencies(): void { $this->view('performance/competencies',['title'=>'Competency Library','rows'=>$this->all('SELECT * FROM performance_competency_library ORDER BY category,name')]); }
    public function storeCompetency(): void { $id=Database::insert('INSERT INTO performance_competency_library(name,category,description,level_name,behavioral_indicator,weight,is_active) VALUES(?,?,?,?,?,?,1)',[trim($_POST['name']??''),trim($_POST['category']??''),trim($_POST['description']??''),trim($_POST['level_name']??''),trim($_POST['behavioral_indicator']??''),(float)($_POST['weight']??0)]); Audit::log('create_competency','performance_competency',(int)$id,$_POST); flash('success','Competency saved.'); redirect('/performance/competencies'); }
    public function reviews(): void { $this->view('performance/reviews',['title'=>'Performance Reviews','rows'=>$this->all('SELECT r.*, e.full_name employee_name, p.name period_name FROM performance_reviews r LEFT JOIN employees e ON e.id=r.employee_id LEFT JOIN performance_periods p ON p.id=r.period_id ORDER BY r.id DESC'),'employees'=>$this->employees(),'periods'=>$this->all('SELECT * FROM performance_periods ORDER BY id DESC')]); }
    public function storeReview(): void { $final=(float)($_POST['kpi_score']??0)*(float)($_POST['kpi_weight']??50)/100+(float)($_POST['competency_score']??0)*(float)($_POST['competency_weight']??25)/100+(float)($_POST['goal_score']??0)*(float)($_POST['goal_weight']??15)/100+(float)($_POST['attendance_score']??0)*(float)($_POST['attendance_weight']??10)/100; $id=Database::insert('INSERT INTO performance_reviews(employee_id,period_id,review_type,kpi_score,competency_score,goal_score,attendance_score,final_score,rating,status,manager_comment,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,NOW())',[(int)($_POST['employee_id']??0),(int)($_POST['period_id']??0),$_POST['review_type']??'manager',(float)($_POST['kpi_score']??0),(float)($_POST['competency_score']??0),(float)($_POST['goal_score']??0),(float)($_POST['attendance_score']??0),$final,trim($_POST['rating']??''),$_POST['status']??'draft',trim($_POST['manager_comment']??'')]); Audit::log('create_performance_review','performance_review',(int)$id,$_POST); flash('success','Review saved. Final score: '.$final); redirect('/performance/reviews'); }
    public function calibration(): void { $this->view('performance/calibration',['title'=>'Calibration','rows'=>$this->all('SELECT c.*, r.final_score, e.full_name employee_name FROM performance_calibrations c LEFT JOIN performance_reviews r ON r.id=c.review_id LEFT JOIN employees e ON e.id=r.employee_id ORDER BY c.id DESC'),'reviews'=>$this->all('SELECT r.id, r.final_score, e.full_name employee_name FROM performance_reviews r LEFT JOIN employees e ON e.id=r.employee_id ORDER BY r.id DESC LIMIT 200')]); }
    public function storeCalibration(): void { $id=Database::insert('INSERT INTO performance_calibrations(review_id,calibrated_score,final_rating,notes,approved_by,created_at) VALUES(?,?,?,?,?,NOW())',[(int)($_POST['review_id']??0),(float)($_POST['calibrated_score']??0),trim($_POST['final_rating']??''),trim($_POST['notes']??''),$_SESSION['user']['id']??null]); Audit::log('create_calibration','performance_calibration',(int)$id,$_POST); flash('success','Calibration saved.'); redirect('/performance/calibration'); }
    public function improvement(): void { $this->view('performance/improvement',['title'=>'Improvement Plans','rows'=>$this->all('SELECT p.*, e.full_name employee_name FROM performance_improvement_plans p LEFT JOIN employees e ON e.id=p.employee_id ORDER BY p.id DESC'),'employees'=>$this->employees()]); }
    public function storeImprovement(): void { $id=Database::insert('INSERT INTO performance_improvement_plans(employee_id,issue_gap,expected_improvement,action_plan,start_date,end_date,mentor_user_id,status,created_at) VALUES(?,?,?,?,?,?,?,?,NOW())',[(int)($_POST['employee_id']??0),trim($_POST['issue_gap']??''),trim($_POST['expected_improvement']??''),trim($_POST['action_plan']??''),$_POST['start_date']?:null,$_POST['end_date']?:null,$_SESSION['user']['id']??null,$_POST['status']??'open']); Audit::log('create_improvement_plan','performance_improvement',(int)$id,$_POST); flash('success','Improvement plan saved.'); redirect('/performance/improvement'); }
    public function bonus(): void { $this->view('performance/bonus',['title'=>'Bonus Rules & Recommendations','rows'=>$this->all('SELECT * FROM performance_bonus_rules ORDER BY min_score DESC')]); }
    public function storeBonusRule(): void { $id=Database::insert('INSERT INTO performance_bonus_rules(rating,min_score,max_score,multiplier,max_bonus,minimum_working_months,payroll_component_code,is_active) VALUES(?,?,?,?,?,?,?,1)',[trim($_POST['rating']??''),(float)($_POST['min_score']??0),(float)($_POST['max_score']??0),(float)($_POST['multiplier']??0),(float)($_POST['max_bonus']??0),(int)($_POST['minimum_working_months']??0),trim($_POST['payroll_component_code']??'BONUS_PERFORMANCE')]); Audit::log('create_bonus_rule','performance_bonus_rule',(int)$id,$_POST); flash('success','Bonus rule saved.'); redirect('/performance/bonus'); }
    public function settings(): void { $this->view('performance/settings',['title'=>'Performance Settings']); }
}
